add the ability to add addtional disks. Improved some checks if its in zpool or iscsi mode  - still unlikely good enough for mutliple data stores. disconnect the sessions on vm stop  - if you delete the vms from other hypervisors, iscsid complains    if the session is still connected.

diff --git a/lib/vm-core b/lib/vm-core
--- a/lib/vm-core
+++ b/lib/vm-core
@@ -168,12 +168,12 @@ core::create(){
     while [ -n "${_disk}" ]; do
         case "${_disk_dev}" in 
             zvol)
-                [ "${VM_DS_ZFS}" = "1" ] && zfs::make_zvol "${VM_DS_ZFS_DATASET}/${_name}/${_disk}" "${_disk_size}" "0" "${_zfs_opts}"
-                [ "${VM_DS_ISCSI}" = "1" ] && iscsi::make_zvol "${VM_DS_ZFS_DATASET}/${_name}/${_disk}" "${_disk_size}" "0" "${_zfs_opts}"
+                [ "${VM_ZFS}" = "1" ] && zfs::make_zvol "${VM_DS_ZFS_DATASET}/${_name}/${_disk}" "${_disk_size}" "0" "${_zfs_opts}"
+                [ "${VM_ISCSI}" = "1" ] && iscsi::make_zvol "${VM_DS_ZFS_DATASET}/${_name}/${_disk}" "${_disk_size}" "0" "${_zfs_opts}"
                 ;;
             sparse-zvol)
-                [ "${VM_DS_ZFS}" = "1" ] && zfs::make_zvol "${VM_DS_ZFS_DATASET}/${_name}/${_disk}" "${_disk_size}" "1" "${_zfs_opts}"
-                [ "${VM_DS_ISCSI}" = "1" ] && iscsi::make_zvol "${VM_DS_ZFS_DATASET}/${_name}/${_disk}" "${_disk_size}" "1" "${_zfs_opts}"
+                [ "${VM_ZFS}" = "1" ] && zfs::make_zvol "${VM_DS_ZFS_DATASET}/${_name}/${_disk}" "${_disk_size}" "1" "${_zfs_opts}"
+                [ "${VM_ISCSI}" = "1" ] && iscsi::make_zvol "${VM_DS_ZFS_DATASET}/${_name}/${_disk}" "${_disk_size}" "1" "${_zfs_opts}"
                 ;;
             *)
                 truncate -s "${_disk_size}" "${VM_DS_PATH}/${_name}/${_disk}"
@@ -264,11 +264,13 @@ core::add_disk(){
     # create the disk first, then update config if no problems
     case "${_device}" in
         zvol)
-            zfs::make_zvol "${VM_DS_ZFS_DATASET}/${_name}/disk${_num}" "${_size}" "0" "${_zfs_opts}"
+            [ "${VM_ZFS}" = "1" ] && zfs::make_zvol "${VM_DS_ZFS_DATASET}/${_name}/disk${_num}" "${_size}" "0" "${_zfs_opts}"
+            [ "${VM_ISCSI}" = "1" ] && iscsi::make_zvol "${VM_DS_ZFS_DATASET}/${_name}/disk${_num}" "${_size}" "0" "${_zfs_opts}"
             _diskname="disk${_num}"
             ;;
         sparse-zvol)
-            zfs::make_zvol "${VM_DS_ZFS_DATASET}/${_name}/disk${_num}" "${_size}" "1" "${_zfs_opts}"
+            [ "${VM_ZFS}" = "1" ]  && zfs::make_zvol "${VM_DS_ZFS_DATASET}/${_name}/disk${_num}" "${_size}" "1" "${_zfs_opts}"
+            [ "${VM_ISCSI}" = "1" ] && iscsi::make_zvol "${VM_DS_ZFS_DATASET}/${_name}/disk${_num}" "${_size}" "1" "${_zfs_opts}"
             _diskname="disk${_num}"
             ;;
         file)
@@ -281,11 +283,15 @@ core::add_disk(){
             ;;
     esac
 
-    # update configuration
-    config::set "${_name}" "disk${_num}_name" "${_diskname}"
+    if [ "${VM_ZFS}" = "1" ]; then
+        # update configuration
+        # iscsi updates the config in make_zvol.
+        config::set "${_name}" "disk${_num}_name" "${_diskname}"
+        config::set "${_name}" "disk${_num}_dev" "${_device}" "1"
+        [ $? -eq 0 ] || util::err "disk image created but errors while updating guest configuration"
+    fi
+
     config::set "${_name}" "disk${_num}_type" "${_emulation}" "1"
-    config::set "${_name}" "disk${_num}_dev" "${_device}" "1"
-    [ $? -eq 0 ] || util::err "disk image created but errors while updating guest configuration"
 }
 
 # add network interface to guest
diff --git a/lib/vm-iscsi b/lib/vm-iscsi
--- a/lib/vm-iscsi
+++ b/lib/vm-iscsi
@@ -221,12 +221,20 @@ iscsi::rename_dataset(){
 }
 
 # mount an iSCSI LUN on FreeBSD hypervisor
-#
-
 iscsi::mount_lun(){
     local _name="$1"
     local _num="$2"
-
+    local _disconnet="$3"
+    local _connect="$4"
+    
+    # ensure legacy defaults
+    if [ "x${_disconnet}" = "x" ]; then
+        _disconnet=1
+    fi
+    if [ "x${_connect}" = "x" ]; then
+        _connect=1
+    fi
+    
     _vmname="$_name"
 
     if [ -c "${_disk}" ]; then
@@ -234,7 +242,6 @@ iscsi::mount_lun(){
     fi
 
     config::load "${vm_iscsi_config}/${_name}/${_name}.conf"
-
     config::get "_disk" "disk${_num}_name"
     config::get "_type" "disk${_num}_type"
     config::get "_diskserial" "disk${_num}_serial"
@@ -244,30 +251,51 @@ iscsi::mount_lun(){
     fi
 
     iscsi::parts_make_zvol "${VM_DS_ZFS_DATASET}/${_name}/disk${_num}"
+    
     _host="${_iqn%%:*}"
     _iqn="${_iqn##*:}"
 
     # Force disconnect the iSCSI session - and silently fail. If it had previously failed, there
     # might be a stale connection config laying around.
-    /usr/bin/iscsictl -R -p "${_host}" -t "${_iqn}:${_vmname}-disk${_num}" > /dev/null 2>&1
-
-    # Connect the iSCSI session
-    /usr/bin/iscsictl -A -p "${_host}" -t "${_iqn}:${_vmname}-${_disk}"
-    [ $? -ne 0 ] && util::err "failed to create ISCSI target ${_vmname}-${_disk} (iscsictl)"
-    sleep 0.2
-    retry=5
-    while [ ! -c "/dev/diskid/DISK-${_diskserial}" -a $retry -ne 0 ]; do
-        retry=$(($retry-1))
-        util::info "Waiting for iSCSI Target to connect ($retry) ..."
-        sleep 0.5
-    done
-    if [ ! -c "/dev/diskid/DISK-${_diskserial}" ]; then
-        util::err "failed to connect to the iSCSI target ${_vmname}-${_disk}"
-    else
-        util::info "iSCSI Target to connected as /dev/diskid/DISK-${_diskserial}"
+    if [ "$_disconnect" = "1" ]; then
+        /usr/bin/iscsictl -R -p "${_host}" -t "${_iqn}:${_vmname}-disk${_num}" > /dev/null 2>&1
     fi
 
+    # Connect the iSCSI session
+    if [ "$_connect" = "1" ]; then
+        /usr/bin/iscsictl -A -p "${_host}" -t "${_iqn}:${_vmname}-${_disk}"
+        [ $? -ne 0 ] && util::err "failed to create ISCSI target ${_vmname}-${_disk} (iscsictl)"
+        sleep 0.2
+        retry=5
+        while [ ! -c "/dev/diskid/DISK-${_diskserial}" -a $retry -ne 0 ]; do
+            retry=$(($retry-1))
+            util::info "Waiting for iSCSI Target to connect ($retry) ..."
+            sleep 0.5
+        done
+        if [ ! -c "/dev/diskid/DISK-${_diskserial}" ]; then
+            util::err "failed to connect to the iSCSI target ${_vmname}-${_disk}"
+        else
+            util::info "iSCSI Target to connected as /dev/diskid/DISK-${_diskserial}"
+        fi
+    fi
 }
+
+# mount an iSCSI LUN on FreeBSD hypervisor
+iscsi::connect_session(){
+    local _name="$1"
+    local _num="$2"
+    local _disconnet=1
+    local _connect=1
+    iscsi::mount_lun "${_name}" "${_num}" "${_disconnect}"  "$_connect"
+}
+iscsi::disconnect_session(){ 
+    local _name="$1"
+    local _num="$2"
+    local _disconnet=1
+    local _connect=0
+    iscsi::mount_lun "${_name}" "${_num}" "${_disconnect}"  "$_connect"
+}
+
 
 # make a zvol for a guest disk image
 #
@@ -291,7 +319,9 @@ iscsi::make_zvol(){
     _host="${_iqn%%:*}"
     _iqn="${_iqn##*:}"
 
-#    config::get "_uuid" "uuid" 
+    if [ -z  "$_uuid" ]; then
+        config::get "_uuid" "uuid" 
+    fi
     iscsi::parts_uuid "$_uuid"
     _disknum=`echo "${_disk}" | sed -e 's/^disk//g'`
     _disknum_pad=`printf "%02d" "${_disknum}"`
@@ -306,7 +336,7 @@ iscsi::make_zvol(){
     ${vm_iscsi_binpath}/${vm_iscsi_bin_create_target} --host "${_host}" --uuid "${_uuid}" --diskserial "${_diskserial}" --vmname "${_vmname}" --name "${_vmname}-${_disk}"
     [ $? -ne 0 ] && util::err "failed to create ISCSI target ${_vmname}-${_disk} (vm_iscsi_bin_create_target)"
 
-    iscsi::mount_lun()  "${_name}" "${_disknum}"
+    # iscsi::mount_lun()  "${_name}" "${_disknum}"
 }
 
 
